In [1]:
import numpy as np
import ngsolve as ng
from fiberamp.fiber.microstruct.pbg import ARF2
from ngsolve.webgui import Draw

importing NGSolve-6.2.2203-56-g47f483033


In [2]:
es = np.linspace(.002, .9999, 240)

In [3]:
es[11]

0.0479284518828452

In [9]:
scaling = 15
n_glass = 1.4388164768221814
n_air = 1.00027717

T_extra = 5 / scaling
T_buffer = 10 / scaling
T_outer = 10 / scaling
n0 = n_air  # Sets buffer and outer region refractive index.

outer_materials = [
    # {'material': 'extra_glass',
    #  'n': n_glass,
    #  'T': T_extra,
    #  'maxh': .05},

    {'material': 'buffer',
     'n': n0,
     'T': T_buffer,
     'maxh': .4},

    {'material': 'Outer',
     'n': n0,
     'T': T_outer,
     'maxh': 1}
]


In [35]:
i = 200
A = ARF2(name='fine_cladding', poly_core=True, e=es[i], shift_capillaries=True,
        outer_materials=outer_materials, T_cladding=11)

ModeSolver: Checking if mesh has required regions
Mesh has  22519  elements,  11287  points,  and  33805  edges.


In [36]:
Draw(ng.CF([0]),A.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [37]:
center = 4.84
radius = .08        
alpha = 5


In [52]:
# Embedding parameter array

E = np.linspace(0.002, .9999, 240)

# Linear fit for finding search centers
m, b = -0.28106463,  5.0825956

# Seach centers
centers = b + m * E
centers[50]

5.023356819217615

In [38]:
betas, zsqrs, E, phi, _ = A.leakyvecmodes(ctr=center, rad=radius, alpha=alpha,
                                          nspan=4, npts=4, p=1, niterations=10,
                                          rhoinv=.99, quadrule='ellipse_trapez_shift',
                                          nrestarts=0, stop_tol=1e-9)


Set NGSolve automatic PML with p= 1  alpha= 5 and thickness=0.667
Using FEAST to search for vector leaky modes in
circle of radius 0.08 centered at  4.84
assuming not more than 4 modes in this interval
System size: 112648  x  112648   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule on elliptical contour
SpectralProjNGR:   Making resolvent at z =  +4.897 +0.001j
SpectralProjNGR:   Making resolvent at z =  +4.783 +0.001j
SpectralProjNGR:   Making resolvent at z =  +4.783 -0.001j
SpectralProjNGR:   Making resolvent at z =  +4.897 -0.001j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [1.0e-03 2.6e-04 3.4e-07 3.7e-05]
   Real part of computed eigenvalues:
   [4.71742895 4.83226385 4.84778712 4.84792169]
   Imag part of computed eigenvalues:
   [-7.62671855e-03 -6.30048819e-03  4.30883834e-06 -4.26226338e-05]
   Relative Hausdorff distance from prior iterate:

In [39]:
for f in phi:
    Draw(1e1*f, A.mesh, min=0, max=1)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [40]:
for e in E:
    Draw(e.imag, A.mesh, vectors={'grid_size':200}, min=0, max=.1)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

Center interpolation for T_clad = 11

es(1) = 5.082
es(25) = 5.053
es(50) = 5.0233
es(75) = 4.9934
es(100) = 4.9638
es(150) = 4.905
es(200) = 4.847
es(239) = 4.803

In [47]:
xs = [es[1], es[25], es[50], es[75], es[100], es[150], es[200], es[239]]
ys = [5.082, 5.053, 5.0233, 4.9934, 4.9638, 4.905, 4.847, 4.803]

In [48]:
xs, ys

([0.006175313807531381,
  0.10638284518828453,
  0.21076569037656906,
  0.31514853556485356,
  0.4195313807531381,
  0.6282970711297071,
  0.8370627615062762,
  0.9999],
 [5.082, 5.053, 5.0233, 4.9934, 4.9638, 4.905, 4.847, 4.803])

In [49]:
np.polyfit(xs, ys,1)

array([-0.28106463,  5.0825956 ])