In [16]:
import numpy as np
import ngsolve as ng
from fiberamp.fiber.microstruct.pbg import ARF2
from ngsolve.webgui import Draw

In [17]:
es = np.linspace(.002, .9999, 240)

In [38]:
es[11]

0.0479284518828452

In [53]:
A = ARF2(name='fine_cladding', poly_core=True, e=es[-50])

ModeSolver: Checking if mesh has required regions
Mesh has  21681  elements,  10859  points,  and  32539  edges.


In [54]:
Draw(ng.CF([0]),A.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [55]:
center = 5.066
radius = .1        
alpha = 5


In [59]:
betas, zsqrs, E, phi, _ = A.leakyvecmodes(ctr=center, rad=radius, alpha=alpha,
                                          nspan=4, npts=4, p=1, niterations=10,
                                          rhoinv=.99, quadrule='ellipse_trapez_shift',
                                          nrestarts=0, stop_tol=1e-9)


Set NGSolve automatic PML with p= 1  alpha= 5 and thickness=2.000
Using FEAST to search for vector leaky modes in
circle of radius 0.1 centered at  5.066
assuming not more than 4 modes in this interval
System size: 108440  x  108440   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule on elliptical contour
SpectralProjNGR:   Making resolvent at z =  +5.137 +0.001j
SpectralProjNGR:   Making resolvent at z =  +4.995 +0.001j
SpectralProjNGR:   Making resolvent at z =  +4.995 -0.001j
SpectralProjNGR:   Making resolvent at z =  +5.137 -0.001j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [8.4e-04 6.1e-05 1.7e-14 1.4e-10]
   Real part of computed eigenvalues:
   [4.22068127 4.70366444 5.06726644 5.06728576]
   Imag part of computed eigenvalues:
   [-3.91768568e-02 -7.15408895e-03 -5.67855185e-06 -4.19055932e-06]
   Relative Hausdorff distance from prior iterate:

In [60]:
for f in phi:
    Draw(1e1*f, A.mesh, min=0, max=1)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [63]:
for e in E:
    Draw(e.imag, A.mesh, vectors={'grid_size':200}, min=0, max=.1)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…