In [1]:
from fiberamp.fiber.microstruct.bragg import Bragg
from fiberamp.fiber import sellmeier
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

importing NGSolve-6.2.2203-56-g47f483033


In [2]:
n_air = 1.00027717
n_glass = 1.4388164768221814

ts=[15*2.7183333333333333e-6, 15*2/3*1e-6, 15*1e-6, 15*1e-6]
ns=[lambda x: n_air, lambda x: n_glass, lambda x: n_air, lambda x: n_air]
maxhs=[.1, .01, .04, .06]
scale=15e-6

In [18]:
goodwl = 1.6999999999999998e-06
goodbeta = 55.44793711650212-1.5343515969487227e-05j

badwl = 1.72372210e-06
badbeta = 54.63752396621695-0.010762057602262157j

trial = 'bad'

if trial == 'good':
    wl = goodwl
    beta = goodbeta
elif trial == 'bad':
    wl = badwl
    beta = badbeta
else:
    raise ValueError

In [19]:
B = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, wl=wl)

ModeSolver: Checking if mesh has required regions
Mesh has  31624  elements,  15865  points,  and  47488  edges.


In [20]:
Draw(B.index, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [21]:
exact = B.sqrZfrom(beta/B.L)

In [22]:
beta

(54.63752396621695-0.010762057602262157j)

In [23]:
guess = exact.conjugate()
guess

(5.961867149537284-1.1760243603388119j)

In [24]:
center = guess
radius = .1
nspan = 4
npts = 2
p = 1

In [25]:
beta, zs, Es, phis,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=10,
#                                        rhoinv=.9,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=4, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve automatic PML with alpha= 10 and thickness=1.000
Using FEAST to search for vector leaky modes in
circle of radius 0.1 centered at  (5.961867149537284-1.1760243603388119j)
assuming not more than 4 modes in this interval
System size: 158224  x  158224   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.1, Center=5.96187-1.17602j
SpectralProjNGR:   Making resolvent at z =  +5.962 -1.076j
SpectralProjNGR:   Making resolvent at z =  +5.962 -1.276j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [0. 0. 0. 0.]
   Real part of computed eigenvalues:
   [5.6009929  6.21812087 6.41491459 6.44674154]
   Imag part of computed eigenvalues:
   [-0.80319041 -1.2206948  -1.06110319 -0.79477555]
   Relative Hausdorff distance from prior iterate: 1.619e+99

 ITERATION 2 with 4 vectors and 4 left vectors
   Duri

In [26]:
for e in Es:
    Draw(e.real, B.mesh, vectors={'grid_size' : 200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [27]:
for phi in phis:
    Draw(1e1*phi, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…