# Hollow Glass tube, glass extending infinitely

In [50]:
from fiberamp.fiber.microstruct.bragg import Bragg
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

In [51]:
n_air = 1.00027717
n_glass = 1.4388164768221814

In [71]:
d = 15*2/3*1e-6
ts=[15*2.7183333333333333e-6, d, 15*1e-6]
ns=[lambda x: n_air, lambda x: n_glass, lambda x: n_glass]
mats=['air','glass','Outer']
maxhs=[.2, .02, .1]
scale=15e-6

In [72]:
i = 0
wls = np.linspace(1.4, 2, 301) * 1e-6

In [73]:
B = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, mats=mats, wl=wls[i])

ModeSolver: Checking if mesh has required regions
Mesh has  9727  elements,  4897  points,  and  14623  edges.


In [74]:
Draw(B.index, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [75]:
exact_betas = np.load("../wavelength/N0/exact_scaled_betas.npy")

In [76]:
exact_zs = B.sqrZfrom(exact_betas / B.L)

In [91]:
center = exact_zs[i]
radius = .05
nspan = 4
npts = 2
p = 2

In [95]:
beta, zs, Es, phis,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=1,
                                       nspan=nspan, npts=npts,
                                       niterations=4, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve automatic PML with alpha= 1 and thickness=1.000
Using FEAST to search for vector leaky modes in
circle of radius 0.05 centered at  (4848.342367014139+0.012689514720893767j)
assuming not more than 4 modes in this interval
System size: 102231  x  102231   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.05, Center=4848.34+0.0126895j
SpectralProjNGR:   Making resolvent at z = +4848.342 +0.063j
SpectralProjNGR:   Making resolvent at z = +4848.342 -0.037j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [4.0e+00 5.6e-01 3.6e-07 1.0e-04]
   Real part of computed eigenvalues:
   [4848.34273328 4848.34276179 4849.55480718 4850.25441971]
   Imag part of computed eigenvalues:
   [-0.01372394 -0.01366118 -0.04933272 -0.03889499]
   Relative Hausdorff distance from prior iterate: 2.063e+96

 ITERATION 2 

In [96]:
for e in Es:
    Draw(e.real, B.mesh, vectors={'grid_size' : 200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [97]:
for phi in phis:
    Draw(1e1*phi, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…